version: "3"

services:

  web_1:
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    command: python app.py
    ports:
      - "8080:5000"
    volumes:
      - .:/code
      - ./images:/images
    links:
      - db
      - redis
    environment:
      - SERVER_ID=1

  web_2:
    build:
      context: .
      dockerfile: dockerfiles/web/Dockerfile
    command: python app.py
    ports:
      - "8081:5000"
    volumes:
      - .:/code
      - ./images:/images
    links:
      - db
      - redis
    environment:
      - SERVER_ID=2

  worker:
    build:
      context: .
      dockerfile: dockerfiles/worker/Dockerfile
    command: rq worker -u 'redis://redis'
    volumes:
      - .:/code
      - ./images:/images
    links:
      - db
      - redis

  db:
    image: mongo:latest


  redis:
    image: redis:alpine

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

